version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  kiii-project-backend-service:
    image: prodanovg/kiii-2025-project-backend:latest
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/admin
      FLASK_APP: app:create_app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  kiii-project-frontend-service:
    image: prodanovg/kiii-2025-project-frontend:latest
    depends_on:
      - kiii-project-backend-service
    ports:
      - "3000:80"
    environment:
      - LOCAL=true
      - VITE_BACKEND_URL=/api

#  nginx:
#    image: nginx:stable-alpine
#    ports:
#      - "80:80"
#    depends_on:
#      - kiii-project-frontend-service
#      - kiii-project-backend-service
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./frontend/my-app/dist:/usr/share/nginx/html:ro

volumes:
  pgdata: